version: 0.0
os: linux

files:
  - source: target/lab2-webapp.war
    destination: /var/lib/tomcat10/webapps/

hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root