version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn clean install
      - mvn package

artifacts:
  files:
    - target/*.war
    - appspec.yml
    - install_dependencies.sh
    - start_server.sh
    - stop_server.sh